---
title: "Filtering and QC"
output: html_document
date: "2025-04-23"
params:
  data_dir: "input/"
  output_rds: "output/filtered_pbmc.rds"
  min_feat: 200
  max_feat: 2500
  max_mt: 5
---

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(here)
```


```{r}
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = params$data_dir)

# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc
```

```{r}
# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
```

```{r}
# Show QC metrics for the first 5 cells
head(pbmc@meta.data, 5)
```

```{r}
# Visualize QC metrics as a violin plot
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

```{r}
pbmc <- subset(pbmc, subset = nFeature_RNA > params$min_feat &
                              nFeature_RNA < params$max_feat &
                              percent.mt < params$max_mt)
```


```{r}
# Force output paths to absolute
output_rds <- normalizePath(params$output_rds, mustWork = FALSE)

# Make sure the output folder exists
if (!dir.exists(dirname(output_rds))) {
  dir.create(dirname(output_rds), recursive = TRUE)
}

# Save object
saveRDS(pbmc, file = output_rds)
```

